/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as LocalCheckoutIdRouteImport } from "./routes/local/$checkoutId";
import { Route as ReposOwnerRepoPullsNumberRouteImport } from "./routes/repos/$owner/$repo/pulls/$number";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const LocalCheckoutIdRoute = LocalCheckoutIdRouteImport.update({
  id: "/local/$checkoutId",
  path: "/local/$checkoutId",
  getParentRoute: () => rootRouteImport,
} as any);
const ReposOwnerRepoPullsNumberRoute =
  ReposOwnerRepoPullsNumberRouteImport.update({
    id: "/repos/$owner/$repo/pulls/$number",
    path: "/repos/$owner/$repo/pulls/$number",
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/local/$checkoutId": typeof LocalCheckoutIdRoute;
  "/repos/$owner/$repo/pulls/$number": typeof ReposOwnerRepoPullsNumberRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/local/$checkoutId": typeof LocalCheckoutIdRoute;
  "/repos/$owner/$repo/pulls/$number": typeof ReposOwnerRepoPullsNumberRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/local/$checkoutId": typeof LocalCheckoutIdRoute;
  "/repos/$owner/$repo/pulls/$number": typeof ReposOwnerRepoPullsNumberRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/local/$checkoutId" | "/repos/$owner/$repo/pulls/$number";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/local/$checkoutId" | "/repos/$owner/$repo/pulls/$number";
  id:
    | "__root__"
    | "/"
    | "/local/$checkoutId"
    | "/repos/$owner/$repo/pulls/$number";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  LocalCheckoutIdRoute: typeof LocalCheckoutIdRoute;
  ReposOwnerRepoPullsNumberRoute: typeof ReposOwnerRepoPullsNumberRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/local/$checkoutId": {
      id: "/local/$checkoutId";
      path: "/local/$checkoutId";
      fullPath: "/local/$checkoutId";
      preLoaderRoute: typeof LocalCheckoutIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repos/$owner/$repo/pulls/$number": {
      id: "/repos/$owner/$repo/pulls/$number";
      path: "/repos/$owner/$repo/pulls/$number";
      fullPath: "/repos/$owner/$repo/pulls/$number";
      preLoaderRoute: typeof ReposOwnerRepoPullsNumberRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocalCheckoutIdRoute: LocalCheckoutIdRoute,
  ReposOwnerRepoPullsNumberRoute: ReposOwnerRepoPullsNumberRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
